### ISSUE TITLE
Demo app should provide a configuration folder without deprecated elements

### ISSUE THREAD

**Issue by fergonco** [geoladris/apps#1]
public-conf.json instead of plugin-conf.json
Take the configuration from the webinar.

**Comment by victorzinho** [comment]
What I did (not pushed yet):
- Reconfigure layers. Only Base Layers (Blue Marble, Open Cycle Map and Google Maps) and Admin (Limits and Fires).
- Removed `layers-editor` and `feedback` plugins.
- Fixed (almost all) `tour` steps.

Problems with the tour:
- Missing limits layer info (`/static/loc/en/html/ign.html`).
- Missing limits legend (`/static/loc/en/images/lim_prov.png`).
- A single temporal layer. A bit weird to have the map in 2013 and the single temporal layer in 2012.
- There are no indicators, so the last two steps don't work.
